version: "3.8"

#Credentials should not be provided in plaintext - should update as env variable
services:
  database-sql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=estonian_card
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: sql_container

  database-mongoDB:
    image: mongo:6-jammy
    ports: [27017:27017]
    container_name: mongo_container
    volumes:
      - dbdata6:/data/db

  application:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - database-sql
      - database-mongoDB

volumes:
  dbdata6:
  db:
    driver: local
